allowBuilds:
  "@heroui-pro/react": true
  '@shopify/react-native-skia': true
  '@zowe/secrets-for-zowe-sdk': true
  esbuild: true
  heroui-native-pro: true
  heroui-pro: true
  unrs-resolver: true

patchedDependencies:
  expo-quick-actions@6.0.2: patches/expo-quick-actions@6.0.2.patch
  react-native-health-connect@4.1.3: patches/react-native-health-connect@4.1.3.patch
