import type { LibraryExercise } from "./types";

/** Bump when entries are added or changed so installed databases can re-seed. */
export const LIBRARY_VERSION = 1;

export const library: readonly LibraryExercise[] = [
  // ─── Chest ────────────────────────────────────────────────────────────────
  // Flat and decline pressing
  {
    id: "barbell-bench-press",
    name: "Barbell Bench Press",
    aliases: ["Bench Press", "Flat Bench Press", "BB Bench"],
    equipment: "barbell",
    pattern: "horizontalPress",
    muscles: { chest: 1, triceps: 0.5, frontDelts: 0.5 },
    reps: [6, 10],
    cue: "Pin shoulder blades back; touch low chest; drive feet into the floor.",
  },
  {
    id: "barbell-bench-press-paused",
    name: "Paused Bench Press",
    aliases: ["Pause Bench"],
    equipment: "barbell",
    pattern: "horizontalPress",
    muscles: { chest: 1, triceps: 0.5, frontDelts: 0.5 },
    reps: [4, 8],
    cue: "Hold a still one-count pause on the chest, then press without bouncing.",
  },
  {
    id: "barbell-decline-bench-press",
    name: "Decline Barbell Bench Press",
    aliases: ["Decline Bench Press"],
    equipment: "barbell",
    pattern: "horizontalPress",
    muscles: { chest: 1, triceps: 0.5 },
    reps: [6, 10],
    cue: "Lock legs in; lower to the lower chest and press back over the shoulders.",
  },
  {
    id: "db-bench-press",
    name: "Dumbbell Bench Press",
    aliases: ["DB Bench Press", "Flat Dumbbell Press"],
    equipment: "dumbbell",
    pattern: "horizontalPress",
    muscles: { chest: 1, triceps: 0.5, frontDelts: 0.5 },
    reps: [8, 12],
    cue: "Lower to chest level for a deep stretch; press up and slightly in.",
  },
  {
    id: "db-decline-bench-press",
    name: "Decline Dumbbell Press",
    aliases: ["Decline DB Press"],
    equipment: "dumbbell",
    pattern: "horizontalPress",
    muscles: { chest: 1, triceps: 0.5 },
    reps: [8, 12],
    cue: "Keep shoulders pinned to the bench; lower wide and press to lockout.",
  },
  {
    id: "db-bench-press-single",
    name: "Single-Arm Dumbbell Bench Press",
    aliases: ["One-Arm Dumbbell Bench Press"],
    equipment: "dumbbell",
    pattern: "horizontalPress",
    muscles: { chest: 1, triceps: 0.5, frontDelts: 0.5 },
    unilateral: true,
    reps: [8, 12],
    cue: "Brace hard so hips stay level; lower to a full stretch and press.",
  },
  {
    id: "db-floor-press",
    name: "Dumbbell Floor Press",
    equipment: "dumbbell",
    pattern: "horizontalPress",
    muscles: { chest: 1, triceps: 0.5 },
    reps: [8, 12],
    cue: "Let upper arms touch the floor softly, pause, then press.",
  },
  {
    id: "db-squeeze-press",
    name: "Dumbbell Squeeze Press",
    aliases: ["Crush Press"],
    equipment: "dumbbell",
    pattern: "horizontalPress",
    muscles: { chest: 1, triceps: 0.5 },
    reps: [10, 15],
    cue: "Press the dumbbells together hard the whole rep as you lower and press.",
  },
  {
    id: "smith-bench-press",
    name: "Smith Machine Bench Press",
    aliases: ["Smith Bench Press"],
    equipment: "smith",
    pattern: "horizontalPress",
    muscles: { chest: 1, triceps: 0.5, frontDelts: 0.5 },
    reps: [6, 10],
    cue: "Set the bench so the bar lands on low chest; stack wrists over elbows.",
  },
  {
    id: "machine-chest-press",
    name: "Machine Chest Press",
    aliases: ["Chest Press Machine", "Seated Chest Press"],
    equipment: "machine",
    pattern: "horizontalPress",
    muscles: { chest: 1, triceps: 0.5, frontDelts: 0.5 },
    reps: [8, 12],
    cue: "Set handles at mid-chest; keep shoulder blades back and press smoothly.",
  },
  {
    id: "plate-loaded-chest-press",
    name: "Plate-Loaded Chest Press",
    aliases: ["Hammer Strength Chest Press", "Iso-Lateral Chest Press"],
    equipment: "plateLoaded",
    pattern: "horizontalPress",
    muscles: { chest: 1, triceps: 0.5, frontDelts: 0.5 },
    reps: [8, 12],
    cue: "Adjust the seat so handles line up with mid-chest; drive through the palms.",
  },
  {
    id: "plate-loaded-decline-press",
    name: "Plate-Loaded Decline Press",
    aliases: ["Hammer Strength Decline Press"],
    equipment: "plateLoaded",
    pattern: "horizontalPress",
    muscles: { chest: 1, triceps: 0.5 },
    reps: [8, 12],
    cue: "Drive the handles down and forward along the arc; keep shoulders pinned.",
  },
  {
    id: "cable-chest-press",
    name: "Cable Chest Press",
    aliases: ["Standing Cable Press"],
    equipment: "cable",
    pattern: "horizontalPress",
    muscles: { chest: 1, triceps: 0.5, frontDelts: 0.5 },
    reps: [10, 15],
    cue: "Stagger your stance; press handles forward and together at chest height.",
  },
  {
    id: "push-up",
    name: "Push-Up",
    aliases: ["Press-Up", "Weighted Push-Up"],
    equipment: "bodyweight",
    load: "bodyweight",
    pattern: "horizontalPress",
    muscles: { chest: 1, triceps: 0.5, frontDelts: 0.5 },
    reps: [10, 20],
    cue: "Hold a straight line from head to heels; lower until the chest nearly touches.",
  },
  {
    id: "deficit-push-up",
    name: "Deficit Push-Up",
    aliases: ["Push-Up on Handles"],
    equipment: "bodyweight",
    load: "bodyweight",
    pattern: "horizontalPress",
    muscles: { chest: 1, triceps: 0.5, frontDelts: 0.5 },
    reps: [8, 15],
    cue: "Hands on handles or plates so the chest sinks below hand level.",
  },

  // Incline pressing
  {
    id: "barbell-incline-bench-press",
    name: "Incline Barbell Bench Press",
    aliases: ["Incline Bench Press", "Incline Bench"],
    equipment: "barbell",
    pattern: "inclinePress",
    muscles: { chest: 1, frontDelts: 0.5, triceps: 0.5 },
    reps: [6, 10],
    cue: "Set the bench near 30°; lower to the upper chest with elbows slightly tucked.",
  },
  {
    id: "db-incline-bench-press",
    name: "Incline Dumbbell Press",
    aliases: ["Incline DB Press", "Incline Dumbbell Bench Press"],
    equipment: "dumbbell",
    pattern: "inclinePress",
    muscles: { chest: 1, frontDelts: 0.5, triceps: 0.5 },
    reps: [8, 12],
    cue: "Bench at 30–45°; lower to a deep stretch beside the upper chest, then press.",
  },
  {
    id: "db-low-incline-press",
    name: "Low-Incline Dumbbell Press",
    aliases: ["15-Degree Dumbbell Press"],
    equipment: "dumbbell",
    pattern: "inclinePress",
    muscles: { chest: 1, frontDelts: 0.5, triceps: 0.5 },
    reps: [8, 12],
    cue: "Bench at 15–20°; keep elbows about 45° from the torso; control the stretch.",
  },
  {
    id: "smith-incline-press",
    name: "Smith Machine Incline Press",
    aliases: ["Smith Incline Bench Press"],
    equipment: "smith",
    pattern: "inclinePress",
    muscles: { chest: 1, frontDelts: 0.5, triceps: 0.5 },
    reps: [8, 12],
    cue: "Position the bench so the bar touches the upper chest; control each descent.",
  },
  {
    id: "machine-incline-chest-press",
    name: "Incline Machine Chest Press",
    aliases: ["Incline Chest Press Machine"],
    equipment: "machine",
    pattern: "inclinePress",
    muscles: { chest: 1, frontDelts: 0.5, triceps: 0.5 },
    reps: [8, 12],
    cue: "Keep the chest up and shoulders down; take a full stretch at the bottom.",
  },
  {
    id: "plate-loaded-incline-press",
    name: "Plate-Loaded Incline Press",
    aliases: ["Hammer Strength Incline Press", "Iso-Lateral Incline Press"],
    equipment: "plateLoaded",
    pattern: "inclinePress",
    muscles: { chest: 1, frontDelts: 0.5, triceps: 0.5 },
    reps: [8, 12],
    cue: "Keep the upper back tight on the pad; let hands travel back for a deep stretch.",
  },

  // Flyes
  {
    id: "pec-deck",
    name: "Pec Deck",
    aliases: ["Machine Fly", "Pec Fly", "Butterfly Machine"],
    equipment: "machine",
    pattern: "chestFly",
    muscles: { chest: 1 },
    reps: [10, 15],
    cue: "Keep a slight elbow bend; squeeze the handles together and control the stretch.",
  },
  {
    id: "cable-crossover",
    name: "Cable Crossover",
    aliases: ["High-to-Low Cable Fly", "Cable Crossovers"],
    equipment: "cable",
    pattern: "chestFly",
    muscles: { chest: 1 },
    reps: [10, 15],
    cue: "Pulleys high; sweep hands down and together in front of the hips.",
  },
  {
    id: "cable-fly",
    name: "Cable Fly",
    aliases: ["Standing Cable Fly", "Mid Cable Fly"],
    equipment: "cable",
    pattern: "chestFly",
    muscles: { chest: 1 },
    reps: [10, 15],
    cue: "Pulleys at shoulder height; hug a wide arc and meet hands at mid-chest.",
  },
  {
    id: "cable-fly-low-to-high",
    name: "Low-to-High Cable Fly",
    aliases: ["Low Cable Fly", "Upper Chest Cable Fly"],
    equipment: "cable",
    pattern: "chestFly",
    muscles: { chest: 1, frontDelts: 0.5 },
    reps: [10, 15],
    cue: "Pulleys low; scoop hands up and in to upper-chest height, palms up.",
  },
  {
    id: "cable-fly-single",
    name: "Single-Arm Cable Fly",
    aliases: ["One-Arm Cable Fly"],
    equipment: "cable",
    pattern: "chestFly",
    muscles: { chest: 1 },
    unilateral: true,
    reps: [10, 15],
    cue: "Stand side-on; sweep one arm across the body just past the midline.",
  },
  {
    id: "cable-fly-incline",
    name: "Incline Cable Fly",
    aliases: ["Incline Bench Cable Fly"],
    equipment: "cable",
    pattern: "chestFly",
    muscles: { chest: 1, frontDelts: 0.5 },
    reps: [10, 15],
    cue: "Bench at 30° between low pulleys; open wide, then bring hands over upper chest.",
  },
  {
    id: "db-fly",
    name: "Dumbbell Fly",
    aliases: ["Flat Dumbbell Fly", "DB Fly"],
    equipment: "dumbbell",
    pattern: "chestFly",
    muscles: { chest: 1 },
    reps: [10, 15],
    cue: "Soft elbows; lower in a wide arc until the chest stretches, then hug up.",
  },
  {
    id: "db-incline-fly",
    name: "Incline Dumbbell Fly",
    aliases: ["Incline DB Fly"],
    equipment: "dumbbell",
    pattern: "chestFly",
    muscles: { chest: 1 },
    reps: [10, 15],
    cue: "Bench at 30°; open wide with a fixed elbow bend; stop before dumbbells touch.",
  },

  // Dips
  {
    id: "chest-dip",
    name: "Chest Dip",
    aliases: ["Weighted Dip", "Forward-Lean Dip"],
    equipment: "bodyweight",
    load: "bodyweight",
    pattern: "dip",
    muscles: { chest: 1, triceps: 0.5, frontDelts: 0.5 },
    reps: [6, 12],
    cue: "Lean forward, let elbows flare slightly, and descend until the chest stretches.",
  },
  {
    id: "assisted-dip",
    name: "Assisted Dip",
    aliases: ["Assisted Dip Machine"],
    equipment: "machine",
    load: "assisted",
    pattern: "dip",
    muscles: { chest: 1, triceps: 0.5, frontDelts: 0.5 },
    reps: [8, 12],
    cue: "Kneel on the pad; lower until shoulders dip below elbows, then press up.",
  },

  // ─── Back ─────────────────────────────────────────────────────────────────
  // Rows
  {
    id: "barbell-row",
    name: "Barbell Row",
    aliases: ["Bent-Over Row", "Barbell Bent-Over Row", "BB Row"],
    equipment: "barbell",
    pattern: "horizontalRow",
    muscles: { upperBack: 1, lats: 0.5, biceps: 0.5, rearDelts: 0.5 },
    reps: [6, 10],
    cue: "Hinge to about 45°, brace, and row the bar to the lower ribs.",
  },
  {
    id: "pendlay-row",
    name: "Pendlay Row",
    equipment: "barbell",
    pattern: "horizontalRow",
    muscles: { upperBack: 1, lats: 0.5, biceps: 0.5, rearDelts: 0.5 },
    reps: [5, 8],
    cue: "Torso near parallel; pull each rep explosively from a dead stop on the floor.",
  },
  {
    id: "barbell-row-underhand",
    name: "Underhand Barbell Row",
    aliases: ["Yates Row", "Reverse-Grip Barbell Row"],
    equipment: "barbell",
    pattern: "horizontalRow",
    muscles: { lats: 1, upperBack: 1, biceps: 0.5 },
    reps: [6, 10],
    cue: "Supinated grip, torso fairly upright; drive the elbows back toward the hips.",
  },
  {
    id: "t-bar-row",
    name: "T-Bar Row",
    aliases: ["Landmine Row"],
    equipment: "barbell",
    pattern: "horizontalRow",
    muscles: { upperBack: 1, lats: 0.5, biceps: 0.5, rearDelts: 0.5 },
    reps: [6, 10],
    cue: "Straddle the bar, hinge with a flat back, and pull the handle to the chest.",
  },
  {
    id: "t-bar-row-chest-supported",
    name: "Chest-Supported T-Bar Row",
    aliases: ["Machine T-Bar Row", "Lying T-Bar Row"],
    equipment: "plateLoaded",
    pattern: "horizontalRow",
    muscles: { upperBack: 1, lats: 0.5, biceps: 0.5, rearDelts: 0.5 },
    reps: [8, 12],
    cue: "Keep the chest glued to the pad; drive elbows back and squeeze the shoulder blades.",
  },
  {
    id: "seal-row",
    name: "Barbell Seal Row",
    aliases: ["Seal Row"],
    equipment: "barbell",
    pattern: "horizontalRow",
    muscles: { upperBack: 1, lats: 0.5, biceps: 0.5, rearDelts: 0.5 },
    reps: [8, 12],
    cue: "Lie prone on a high bench; row the bar to the bench without lifting the chest.",
  },
  {
    id: "db-seal-row",
    name: "Dumbbell Seal Row",
    equipment: "dumbbell",
    pattern: "horizontalRow",
    muscles: { upperBack: 1, lats: 0.5, biceps: 0.5, rearDelts: 0.5 },
    reps: [8, 12],
    cue: "Lie flat on a raised bench and row both dumbbells up, elbows at about 45°.",
  },
  {
    id: "chest-supported-db-row",
    name: "Chest-Supported Dumbbell Row",
    aliases: ["Incline Dumbbell Row", "Incline Bench Row"],
    equipment: "dumbbell",
    pattern: "horizontalRow",
    muscles: { upperBack: 1, lats: 0.5, biceps: 0.5, rearDelts: 0.5 },
    reps: [8, 12],
    cue: "Chest on an incline bench; let the shoulder blades reach, then row.",
  },
  {
    id: "db-row-single",
    name: "Single-Arm Dumbbell Row",
    aliases: ["One-Arm Dumbbell Row", "DB Row"],
    equipment: "dumbbell",
    pattern: "horizontalRow",
    muscles: { lats: 1, upperBack: 0.5, biceps: 0.5 },
    unilateral: true,
    reps: [8, 12],
    cue: "Brace on a bench; pull the dumbbell toward the hip, not straight up.",
  },
  {
    id: "db-row-bent-over",
    name: "Bent-Over Dumbbell Row",
    aliases: ["Two-Arm Dumbbell Row"],
    equipment: "dumbbell",
    pattern: "horizontalRow",
    muscles: { upperBack: 1, lats: 0.5, biceps: 0.5, rearDelts: 0.5 },
    reps: [8, 12],
    cue: "Hinge with a neutral spine and row both dumbbells to the lower ribs.",
  },
  {
    id: "meadows-row",
    name: "Meadows Row",
    equipment: "barbell",
    pattern: "horizontalRow",
    muscles: { upperBack: 1, lats: 0.5, biceps: 0.5, rearDelts: 0.5 },
    unilateral: true,
    reps: [8, 12],
    cue: "Stand perpendicular to a landmine; row the sleeve high with the elbow flared.",
  },
  {
    id: "cable-row",
    name: "Seated Cable Row",
    aliases: ["Cable Row", "Seated Row", "V-Grip Cable Row"],
    equipment: "cable",
    pattern: "horizontalRow",
    muscles: { upperBack: 1, lats: 1, biceps: 0.5 },
    reps: [8, 12],
    cue: "Sit tall, let the shoulders reach forward, then pull the handle to the stomach.",
  },
  {
    id: "cable-row-wide",
    name: "Wide-Grip Cable Row",
    aliases: ["Wide-Grip Seated Row"],
    equipment: "cable",
    pattern: "horizontalRow",
    muscles: { upperBack: 1, rearDelts: 0.5, lats: 0.5, biceps: 0.5 },
    reps: [8, 12],
    cue: "Use a wide bar, flare the elbows, and pull to the lower chest.",
  },
  {
    id: "cable-row-single",
    name: "Single-Arm Cable Row",
    aliases: ["One-Arm Cable Row"],
    equipment: "cable",
    pattern: "horizontalRow",
    muscles: { lats: 1, upperBack: 0.5, biceps: 0.5 },
    unilateral: true,
    reps: [8, 12],
    cue: "Reach long at the front, then drive the elbow back past the torso.",
  },
  {
    id: "machine-row",
    name: "Seated Row Machine",
    aliases: ["Machine Row", "Chest-Supported Machine Row"],
    equipment: "machine",
    pattern: "horizontalRow",
    muscles: { upperBack: 1, lats: 0.5, biceps: 0.5, rearDelts: 0.5 },
    reps: [8, 12],
    cue: "Chest on the pad; pull until elbows pass the torso, then reach forward.",
  },
  {
    id: "plate-loaded-row",
    name: "Plate-Loaded Row",
    aliases: ["Hammer Strength Row", "Iso-Lateral Row"],
    equipment: "plateLoaded",
    pattern: "horizontalRow",
    muscles: { upperBack: 1, lats: 0.5, biceps: 0.5, rearDelts: 0.5 },
    reps: [8, 12],
    cue: "Keep the chest on the pad and row each handle to the side of the ribs.",
  },
  {
    id: "plate-loaded-low-row",
    name: "Plate-Loaded Low Row",
    aliases: ["Hammer Strength Low Row", "Iso-Lateral Low Row"],
    equipment: "plateLoaded",
    pattern: "horizontalRow",
    muscles: { lats: 1, upperBack: 0.5, biceps: 0.5 },
    reps: [8, 12],
    cue: "Pull low and toward the hips, keeping the elbows close to the body.",
  },
  {
    id: "smith-row",
    name: "Smith Machine Row",
    aliases: ["Smith Bent-Over Row"],
    equipment: "smith",
    pattern: "horizontalRow",
    muscles: { upperBack: 1, lats: 0.5, biceps: 0.5, rearDelts: 0.5 },
    reps: [8, 12],
    cue: "Hinge with a flat back; pull the bar to the lower ribs along the track.",
  },
  {
    id: "inverted-row",
    name: "Inverted Row",
    aliases: ["Bodyweight Row", "Australian Pull-Up"],
    equipment: "bodyweight",
    load: "bodyweight",
    pattern: "horizontalRow",
    muscles: { upperBack: 1, lats: 0.5, biceps: 0.5, rearDelts: 0.5 },
    reps: [8, 15],
    cue: "Body rigid like a plank; pull the chest to the bar and lower under control.",
  },
  {
    id: "band-row",
    name: "Band Row",
    aliases: ["Banded Row"],
    equipment: "band",
    pattern: "horizontalRow",
    muscles: { upperBack: 1, lats: 0.5, biceps: 0.5 },
    reps: [12, 20],
    cue: "Anchor the band at chest height; squeeze the shoulder blades as elbows go back.",
  },

  // Pulldowns and pull-ups
  {
    id: "lat-pulldown",
    name: "Lat Pulldown",
    aliases: ["Pulldown", "Wide-Grip Pulldown", "Wide-Grip Lat Pulldown"],
    equipment: "cable",
    pattern: "verticalPull",
    muscles: { lats: 1, biceps: 0.5, upperBack: 0.5 },
    reps: [8, 12],
    cue: "Thighs locked under the pad; pull the bar to the upper chest, elbows to your sides.",
  },
  {
    id: "lat-pulldown-close-grip",
    name: "Close-Grip Pulldown",
    aliases: ["V-Bar Pulldown", "Close-Grip Lat Pulldown", "V-Grip Pulldown"],
    equipment: "cable",
    pattern: "verticalPull",
    muscles: { lats: 1, biceps: 0.5, upperBack: 0.5 },
    reps: [8, 12],
    cue: "Lean back slightly and pull the handle to the chest with elbows tight.",
  },
  {
    id: "lat-pulldown-neutral",
    name: "Neutral-Grip Pulldown",
    aliases: ["Neutral-Grip Lat Pulldown", "Parallel-Grip Pulldown"],
    equipment: "cable",
    pattern: "verticalPull",
    muscles: { lats: 1, biceps: 0.5, upperBack: 0.5 },
    reps: [8, 12],
    cue: "Use a wide parallel-grip bar; drive the elbows down toward the back pockets.",
  },
  {
    id: "lat-pulldown-underhand",
    name: "Underhand Pulldown",
    aliases: ["Reverse-Grip Pulldown", "Supinated Pulldown"],
    equipment: "cable",
    pattern: "verticalPull",
    muscles: { lats: 1, biceps: 0.5, upperBack: 0.5 },
    reps: [8, 12],
    cue: "Shoulder-width underhand grip; pull to the upper chest, elbows in front.",
  },
  {
    id: "lat-pulldown-single",
    name: "Single-Arm Cable Pulldown",
    aliases: ["Single-Arm Lat Pulldown", "One-Arm Pulldown"],
    equipment: "cable",
    pattern: "verticalPull",
    muscles: { lats: 1, biceps: 0.5 },
    unilateral: true,
    reps: [8, 12],
    cue: "Reach high for a full stretch, then pull the elbow down to the hip.",
  },
  {
    id: "machine-pulldown",
    name: "Machine Pulldown",
    aliases: ["Pulldown Machine", "Selectorized Pulldown"],
    equipment: "machine",
    pattern: "verticalPull",
    muscles: { lats: 1, biceps: 0.5, upperBack: 0.5 },
    reps: [8, 12],
    cue: "Set the pad snug on the thighs; pull handles to the shoulders and control the rise.",
  },
  {
    id: "plate-loaded-pulldown",
    name: "Plate-Loaded Pulldown",
    aliases: ["Hammer Strength Pulldown", "Iso-Lateral Pulldown"],
    equipment: "plateLoaded",
    pattern: "verticalPull",
    muscles: { lats: 1, biceps: 0.5, upperBack: 0.5 },
    reps: [8, 12],
    cue: "Lean slightly into the stretch, then pull the elbows down and back.",
  },
  {
    id: "plate-loaded-high-row",
    name: "Plate-Loaded High Row",
    aliases: ["Hammer Strength High Row", "Iso-Lateral High Row"],
    equipment: "plateLoaded",
    pattern: "verticalPull",
    muscles: { lats: 1, upperBack: 0.5, biceps: 0.5 },
    reps: [8, 12],
    cue: "Pull the handles down and back toward the hips; stretch fully at the top.",
  },
  {
    id: "pull-up",
    name: "Pull-Up",
    aliases: ["Wide-Grip Pull-Up", "Weighted Pull-Up"],
    equipment: "bodyweight",
    load: "bodyweight",
    pattern: "verticalPull",
    muscles: { lats: 1, biceps: 0.5, upperBack: 0.5 },
    reps: [6, 10],
    cue: "Start from a dead hang; pull the chest toward the bar without kipping.",
  },
  {
    id: "chin-up",
    name: "Chin-Up",
    aliases: ["Weighted Chin-Up", "Underhand Pull-Up"],
    equipment: "bodyweight",
    load: "bodyweight",
    pattern: "verticalPull",
    muscles: { lats: 1, biceps: 0.5, upperBack: 0.5 },
    reps: [6, 10],
    cue: "Palms facing you, shoulder-width; pull until the chin clears the bar.",
  },
  {
    id: "neutral-grip-pull-up",
    name: "Neutral-Grip Pull-Up",
    aliases: ["Hammer-Grip Pull-Up", "Parallel-Grip Pull-Up"],
    equipment: "bodyweight",
    load: "bodyweight",
    pattern: "verticalPull",
    muscles: { lats: 1, biceps: 0.5, upperBack: 0.5 },
    reps: [6, 10],
    cue: "Palms facing each other; lead with the chest and control the descent.",
  },
  {
    id: "assisted-pull-up",
    name: "Assisted Pull-Up",
    aliases: ["Assisted Chin-Up", "Assisted Pull-Up Machine"],
    equipment: "machine",
    load: "assisted",
    pattern: "verticalPull",
    muscles: { lats: 1, biceps: 0.5, upperBack: 0.5 },
    reps: [8, 12],
    cue: "Use enough assistance to reach full range with a smooth tempo.",
  },

  // Pullovers
  {
    id: "straight-arm-pulldown",
    name: "Straight-Arm Pulldown",
    aliases: ["Cable Pullover", "Straight-Arm Cable Pulldown", "Rope Pullover"],
    equipment: "cable",
    pattern: "pullover",
    muscles: { lats: 1 },
    reps: [10, 15],
    cue: "Hinge slightly with arms nearly straight; sweep the bar or rope to the thighs.",
  },
  {
    id: "db-pullover",
    name: "Dumbbell Pullover",
    aliases: ["DB Pullover"],
    equipment: "dumbbell",
    pattern: "pullover",
    muscles: { lats: 1, chest: 0.5 },
    reps: [10, 15],
    cue: "Lower the dumbbell behind the head with soft elbows until the lats stretch.",
  },
  {
    id: "machine-pullover",
    name: "Machine Pullover",
    aliases: ["Pullover Machine", "Nautilus Pullover"],
    equipment: "machine",
    pattern: "pullover",
    muscles: { lats: 1 },
    reps: [10, 15],
    cue: "Drive through the elbow pads in an arc until the bar reaches the stomach.",
  },

  // Shrugs
  {
    id: "barbell-shrug",
    name: "Barbell Shrug",
    equipment: "barbell",
    pattern: "shrug",
    muscles: { traps: 1 },
    reps: [10, 15],
    cue: "Stand tall and lift the shoulders straight up toward the ears; pause briefly.",
  },
  {
    id: "db-shrug",
    name: "Dumbbell Shrug",
    aliases: ["DB Shrug"],
    equipment: "dumbbell",
    pattern: "shrug",
    muscles: { traps: 1 },
    reps: [10, 15],
    cue: "Dumbbells at your sides; shrug straight up, hold a beat, lower slowly.",
  },
  {
    id: "db-shrug-incline",
    name: "Incline Dumbbell Shrug",
    aliases: ["Chest-Supported Shrug"],
    equipment: "dumbbell",
    pattern: "shrug",
    muscles: { traps: 1, upperBack: 0.5 },
    reps: [10, 15],
    cue: "Chest down on an incline bench; pull the shoulder blades up and together.",
  },
  {
    id: "smith-shrug",
    name: "Smith Machine Shrug",
    aliases: ["Smith Shrug"],
    equipment: "smith",
    pattern: "shrug",
    muscles: { traps: 1 },
    reps: [10, 15],
    cue: "Stand close to the bar; lift the shoulders straight up without rolling them.",
  },
  {
    id: "trap-bar-shrug",
    name: "Trap Bar Shrug",
    aliases: ["Hex Bar Shrug"],
    equipment: "trapBar",
    pattern: "shrug",
    muscles: { traps: 1 },
    reps: [10, 15],
    cue: "Stand in the center of the bar and shrug high with the arms long.",
  },
  {
    id: "machine-shrug",
    name: "Machine Shrug",
    aliases: ["Shrug Machine"],
    equipment: "machine",
    pattern: "shrug",
    muscles: { traps: 1 },
    reps: [10, 15],
    cue: "Keep the arms relaxed like hooks; lift from the traps, not the biceps.",
  },
  {
    id: "cable-shrug",
    name: "Cable Shrug",
    equipment: "cable",
    pattern: "shrug",
    muscles: { traps: 1 },
    reps: [12, 15],
    cue: "Stand between low pulleys; shrug up and slightly back, pausing at the top.",
  },

  // ─── Shoulders ────────────────────────────────────────────────────────────
  // Overhead pressing
  {
    id: "barbell-overhead-press",
    name: "Overhead Press",
    aliases: ["OHP", "Military Press", "Standing Barbell Press", "Strict Press"],
    equipment: "barbell",
    pattern: "verticalPress",
    muscles: { frontDelts: 1, triceps: 0.5, sideDelts: 0.5 },
    reps: [6, 10],
    cue: "Squeeze the glutes, press in a straight line, and push the head through at lockout.",
  },
  {
    id: "barbell-seated-overhead-press",
    name: "Seated Barbell Overhead Press",
    aliases: ["Seated Military Press"],
    equipment: "barbell",
    pattern: "verticalPress",
    muscles: { frontDelts: 1, triceps: 0.5, sideDelts: 0.5 },
    reps: [6, 10],
    cue: "Sit upright with the back supported; lower to the chin and press overhead.",
  },
  {
    id: "push-press",
    name: "Push Press",
    equipment: "barbell",
    pattern: "verticalPress",
    muscles: { frontDelts: 1, triceps: 0.5, sideDelts: 0.5 },
    reps: [5, 8],
    cue: "Dip a few inches at the knees, drive up, and finish the press with the arms.",
  },
  {
    id: "db-shoulder-press",
    name: "Seated Dumbbell Shoulder Press",
    aliases: ["Dumbbell Shoulder Press", "DB Shoulder Press", "Dumbbell Overhead Press"],
    equipment: "dumbbell",
    pattern: "verticalPress",
    muscles: { frontDelts: 1, triceps: 0.5, sideDelts: 0.5 },
    reps: [8, 12],
    cue: "Lower until the dumbbells reach ear level; press up without clanking them.",
  },
  {
    id: "db-shoulder-press-standing",
    name: "Standing Dumbbell Shoulder Press",
    aliases: ["Standing DB Press"],
    equipment: "dumbbell",
    pattern: "verticalPress",
    muscles: { frontDelts: 1, triceps: 0.5, sideDelts: 0.5 },
    reps: [8, 12],
    cue: "Brace abs and glutes; press straight up without leaning back.",
  },
  {
    id: "db-shoulder-press-single",
    name: "Single-Arm Dumbbell Shoulder Press",
    aliases: ["One-Arm Dumbbell Press"],
    equipment: "dumbbell",
    pattern: "verticalPress",
    muscles: { frontDelts: 1, triceps: 0.5, sideDelts: 0.5 },
    unilateral: true,
    reps: [8, 12],
    cue: "Resist leaning sideways; press one dumbbell straight overhead.",
  },
  {
    id: "arnold-press",
    name: "Arnold Press",
    equipment: "dumbbell",
    pattern: "verticalPress",
    muscles: { frontDelts: 1, sideDelts: 0.5, triceps: 0.5 },
    reps: [8, 12],
    cue: "Start with palms facing you; rotate them outward as you press overhead.",
  },
  {
    id: "smith-overhead-press",
    name: "Smith Machine Shoulder Press",
    aliases: ["Smith Overhead Press", "Smith Military Press"],
    equipment: "smith",
    pattern: "verticalPress",
    muscles: { frontDelts: 1, triceps: 0.5, sideDelts: 0.5 },
    reps: [8, 12],
    cue: "Set the bench slightly behind the bar path; lower to chin level and press.",
  },
  {
    id: "machine-shoulder-press",
    name: "Machine Shoulder Press",
    aliases: ["Shoulder Press Machine"],
    equipment: "machine",
    pattern: "verticalPress",
    muscles: { frontDelts: 1, triceps: 0.5, sideDelts: 0.5 },
    reps: [8, 12],
    cue: "Seat so the handles start at shoulder height; press up without shrugging.",
  },
  {
    id: "plate-loaded-shoulder-press",
    name: "Plate-Loaded Shoulder Press",
    aliases: ["Hammer Strength Shoulder Press", "Iso-Lateral Shoulder Press"],
    equipment: "plateLoaded",
    pattern: "verticalPress",
    muscles: { frontDelts: 1, triceps: 0.5, sideDelts: 0.5 },
    reps: [8, 12],
    cue: "Keep the back on the pad and ribs down; press through the full range.",
  },
  {
    id: "landmine-press",
    name: "Landmine Press",
    aliases: ["Single-Arm Landmine Press"],
    equipment: "barbell",
    pattern: "verticalPress",
    muscles: { frontDelts: 1, chest: 0.5, triceps: 0.5 },
    unilateral: true,
    reps: [8, 12],
    cue: "Hold the sleeve at the shoulder and press up and forward along the arc.",
  },
  {
    id: "pike-push-up",
    name: "Pike Push-Up",
    equipment: "bodyweight",
    load: "bodyweight",
    pattern: "verticalPress",
    muscles: { frontDelts: 1, triceps: 0.5 },
    reps: [6, 12],
    cue: "Hips high; lower the head just ahead of the hands, then press back up.",
  },

  // Front raises
  {
    id: "db-front-raise",
    name: "Dumbbell Front Raise",
    aliases: ["Front Raise"],
    equipment: "dumbbell",
    pattern: "frontRaise",
    muscles: { frontDelts: 1 },
    reps: [10, 15],
    cue: "Raise to shoulder height with a slight elbow bend; lower slowly.",
  },
  {
    id: "cable-front-raise",
    name: "Cable Front Raise",
    equipment: "cable",
    pattern: "frontRaise",
    muscles: { frontDelts: 1 },
    reps: [10, 15],
    cue: "Face away from a low pulley; raise the handle to eye level with a long arm.",
  },

  // Lateral raises
  {
    id: "db-lateral-raise",
    name: "Dumbbell Lateral Raise",
    aliases: ["Lateral Raise", "Side Raise", "DB Lateral Raise"],
    equipment: "dumbbell",
    pattern: "lateralRaise",
    muscles: { sideDelts: 1 },
    reps: [12, 20],
    cue: "Lead with the elbows and raise out to the sides to shoulder height, no swing.",
  },
  {
    id: "db-lateral-raise-seated",
    name: "Seated Dumbbell Lateral Raise",
    equipment: "dumbbell",
    pattern: "lateralRaise",
    muscles: { sideDelts: 1 },
    reps: [12, 20],
    cue: "Sit tall to remove momentum; raise out and slightly forward.",
  },
  {
    id: "db-lateral-raise-lean-away",
    name: "Lean-Away Dumbbell Lateral Raise",
    equipment: "dumbbell",
    pattern: "lateralRaise",
    muscles: { sideDelts: 1 },
    unilateral: true,
    reps: [12, 20],
    cue: "Hold a post and lean away; raise the dumbbell out to the side.",
  },
  {
    id: "db-lateral-raise-lying",
    name: "Lying Incline Lateral Raise",
    aliases: ["Side-Lying Lateral Raise"],
    equipment: "dumbbell",
    pattern: "lateralRaise",
    muscles: { sideDelts: 1 },
    unilateral: true,
    reps: [12, 20],
    cue: "Lie on your side on an incline bench; raise the arm up in a wide arc.",
  },
  {
    id: "db-y-raise",
    name: "Dumbbell Y-Raise",
    aliases: ["Incline Y-Raise", "Chest-Supported Y-Raise"],
    equipment: "dumbbell",
    pattern: "lateralRaise",
    muscles: { sideDelts: 1, traps: 0.5 },
    reps: [12, 20],
    cue: "Chest on an incline bench; raise the dumbbells in a Y with thumbs up.",
  },
  {
    id: "cable-lateral-raise-single",
    name: "Single-Arm Cable Lateral Raise",
    aliases: ["Cable Lateral Raise", "One-Arm Cable Lateral Raise"],
    equipment: "cable",
    pattern: "lateralRaise",
    muscles: { sideDelts: 1 },
    unilateral: true,
    reps: [12, 20],
    cue: "Set the pulley near hip height; sweep the handle out to shoulder level.",
  },
  {
    id: "cable-lateral-raise-lean-away",
    name: "Lean-Away Cable Lateral Raise",
    equipment: "cable",
    pattern: "lateralRaise",
    muscles: { sideDelts: 1 },
    unilateral: true,
    reps: [12, 20],
    cue: "Hold the frame and lean away; raise from the low pulley out to the side.",
  },
  {
    id: "cable-lateral-raise-behind-back",
    name: "Behind-the-Back Cable Lateral Raise",
    equipment: "cable",
    pattern: "lateralRaise",
    muscles: { sideDelts: 1 },
    unilateral: true,
    reps: [12, 20],
    cue: "Run the cable behind your back from the far side; raise the arm out wide.",
  },
  {
    id: "cable-y-raise",
    name: "Cable Y-Raise",
    aliases: ["Cross-Cable Y-Raise"],
    equipment: "cable",
    pattern: "lateralRaise",
    muscles: { sideDelts: 1 },
    reps: [12, 20],
    cue: "Cross the low cables and raise the hands up and out into a wide Y.",
  },
  {
    id: "machine-lateral-raise",
    name: "Machine Lateral Raise",
    aliases: ["Lateral Raise Machine"],
    equipment: "machine",
    pattern: "lateralRaise",
    muscles: { sideDelts: 1 },
    reps: [12, 20],
    cue: "Align shoulders with the pivot; drive the elbows out and up against the pads.",
  },
  {
    id: "band-lateral-raise",
    name: "Band Lateral Raise",
    equipment: "band",
    pattern: "lateralRaise",
    muscles: { sideDelts: 1 },
    reps: [15, 25],
    cue: "Stand on the band; raise the arms out to the sides and control the return.",
  },

  // Upright rows
  {
    id: "barbell-upright-row",
    name: "Barbell Upright Row",
    aliases: ["Upright Row", "EZ-Bar Upright Row"],
    equipment: "barbell",
    pattern: "lateralRaise",
    muscles: { sideDelts: 1, traps: 0.5 },
    reps: [10, 15],
    cue: "Grip wider than the shoulders and lift the elbows to shoulder height.",
  },
  {
    id: "cable-upright-row",
    name: "Cable Upright Row",
    equipment: "cable",
    pattern: "lateralRaise",
    muscles: { sideDelts: 1, traps: 0.5 },
    reps: [10, 15],
    cue: "Wide grip; pull the elbows up and out to shoulder height, bar close.",
  },
  {
    id: "db-upright-row",
    name: "Dumbbell Upright Row",
    equipment: "dumbbell",
    pattern: "lateralRaise",
    muscles: { sideDelts: 1, traps: 0.5 },
    reps: [10, 15],
    cue: "Lead with the elbows, pulling the dumbbells up the front of the body.",
  },

  // Rear delts
  {
    id: "reverse-pec-deck",
    name: "Reverse Pec Deck",
    aliases: ["Rear Delt Fly Machine", "Reverse Fly Machine", "Rear Delt Machine"],
    equipment: "machine",
    pattern: "rearDeltFly",
    muscles: { rearDelts: 1, upperBack: 0.5 },
    reps: [12, 20],
    cue: "Arms slightly bent; sweep the handles back wide without pinching the blades.",
  },
  {
    id: "cable-rear-delt-fly",
    name: "Cable Rear Delt Fly",
    aliases: ["Cable Reverse Fly", "Reverse Cable Crossover"],
    equipment: "cable",
    pattern: "rearDeltFly",
    muscles: { rearDelts: 1, upperBack: 0.5 },
    reps: [12, 20],
    cue: "Cross the cables at shoulder height and pull the hands apart in a wide arc.",
  },
  {
    id: "cable-rear-delt-fly-single",
    name: "Single-Arm Cable Rear Delt Fly",
    equipment: "cable",
    pattern: "rearDeltFly",
    muscles: { rearDelts: 1 },
    unilateral: true,
    reps: [12, 20],
    cue: "Pull across the body from the opposite pulley, moving the arm out and back.",
  },
  {
    id: "db-rear-delt-fly",
    name: "Bent-Over Dumbbell Reverse Fly",
    aliases: ["Rear Delt Fly", "Dumbbell Reverse Fly", "Rear Delt Raise"],
    equipment: "dumbbell",
    pattern: "rearDeltFly",
    muscles: { rearDelts: 1, upperBack: 0.5 },
    reps: [12, 20],
    cue: "Hinge forward and raise the dumbbells out wide, pinkies leading.",
  },
  {
    id: "db-rear-delt-fly-chest-supported",
    name: "Chest-Supported Reverse Fly",
    aliases: ["Incline Rear Delt Fly"],
    equipment: "dumbbell",
    pattern: "rearDeltFly",
    muscles: { rearDelts: 1, upperBack: 0.5 },
    reps: [12, 20],
    cue: "Chest on an incline bench; raise the dumbbells out to the sides in a wide arc.",
  },
  {
    id: "db-rear-delt-row",
    name: "Dumbbell Rear Delt Row",
    aliases: ["Rear Delt Row"],
    equipment: "dumbbell",
    pattern: "rearDeltFly",
    muscles: { rearDelts: 1, upperBack: 0.5 },
    reps: [10, 15],
    cue: "Flare the elbow to 90° and row the dumbbell toward the upper chest.",
  },
  {
    id: "band-pull-apart",
    name: "Band Pull-Apart",
    equipment: "band",
    pattern: "rearDeltFly",
    muscles: { rearDelts: 1, upperBack: 0.5 },
    reps: [15, 25],
    cue: "Arms straight at shoulder height; pull the band apart until it meets the chest.",
  },
  {
    id: "face-pull",
    name: "Face Pull",
    aliases: ["Cable Face Pull", "Rope Face Pull"],
    equipment: "cable",
    pattern: "facePull",
    muscles: { rearDelts: 1, upperBack: 0.5 },
    reps: [12, 20],
    cue: "Pull the rope toward the eyes, splitting the ends and rotating the hands back.",
  },
  {
    id: "band-face-pull",
    name: "Band Face Pull",
    equipment: "band",
    pattern: "facePull",
    muscles: { rearDelts: 1, upperBack: 0.5 },
    reps: [15, 25],
    cue: "Anchor the band at face height; pull and spread the hands beside the ears.",
  },

  // ─── Arms ─────────────────────────────────────────────────────────────────
  // Biceps
  {
    id: "barbell-curl",
    name: "Barbell Curl",
    aliases: ["BB Curl", "Standing Barbell Curl"],
    equipment: "barbell",
    pattern: "curl",
    muscles: { biceps: 1 },
    reps: [8, 12],
    cue: "Pin the elbows at your sides; curl without swinging the torso.",
  },
  {
    id: "ez-bar-curl",
    name: "EZ-Bar Curl",
    aliases: ["EZ Curl"],
    equipment: "ezBar",
    pattern: "curl",
    muscles: { biceps: 1 },
    reps: [8, 12],
    cue: "Hold the angled grips; curl up and lower all the way under control.",
  },
  {
    id: "ez-bar-preacher-curl",
    name: "EZ-Bar Preacher Curl",
    aliases: ["Preacher Curl"],
    equipment: "ezBar",
    pattern: "curl",
    muscles: { biceps: 1 },
    reps: [8, 12],
    cue: "Armpits snug on the pad; lower until the arms are nearly straight.",
  },
  {
    id: "db-preacher-curl-single",
    name: "Single-Arm Dumbbell Preacher Curl",
    aliases: ["Dumbbell Preacher Curl"],
    equipment: "dumbbell",
    pattern: "curl",
    muscles: { biceps: 1 },
    unilateral: true,
    reps: [10, 15],
    cue: "Brace the upper arm on the pad and curl through a full stretch.",
  },
  {
    id: "machine-preacher-curl",
    name: "Machine Preacher Curl",
    aliases: ["Machine Curl", "Biceps Curl Machine"],
    equipment: "machine",
    pattern: "curl",
    muscles: { biceps: 1 },
    reps: [10, 15],
    cue: "Line the elbows up with the pivot; curl hard and resist on the way down.",
  },
  {
    id: "db-curl",
    name: "Dumbbell Curl",
    aliases: ["Alternating Dumbbell Curl", "DB Curl", "Dumbbell Biceps Curl"],
    equipment: "dumbbell",
    pattern: "curl",
    muscles: { biceps: 1 },
    reps: [8, 12],
    cue: "Turn the palms up as you curl; keep the elbows still near your sides.",
  },
  {
    id: "db-hammer-curl",
    name: "Hammer Curl",
    aliases: ["Dumbbell Hammer Curl"],
    equipment: "dumbbell",
    pattern: "curl",
    muscles: { biceps: 1, forearms: 0.5 },
    reps: [8, 12],
    cue: "Palms face each other; curl without letting the elbows drift forward.",
  },
  {
    id: "cross-body-hammer-curl",
    name: "Cross-Body Hammer Curl",
    equipment: "dumbbell",
    pattern: "curl",
    muscles: { biceps: 1, forearms: 0.5 },
    reps: [8, 12],
    cue: "Curl each dumbbell across the body toward the opposite shoulder.",
  },
  {
    id: "rope-hammer-curl",
    name: "Cable Rope Hammer Curl",
    aliases: ["Rope Hammer Curl"],
    equipment: "cable",
    pattern: "curl",
    muscles: { biceps: 1, forearms: 0.5 },
    reps: [10, 15],
    cue: "Neutral grip on the rope; curl up and pull the ends apart at the top.",
  },
  {
    id: "db-incline-curl",
    name: "Incline Dumbbell Curl",
    aliases: ["Incline Curl"],
    equipment: "dumbbell",
    pattern: "curl",
    muscles: { biceps: 1 },
    reps: [8, 12],
    cue: "Bench at 45–60°; let the arms hang behind the torso for a deep stretch.",
  },
  {
    id: "db-concentration-curl",
    name: "Concentration Curl",
    aliases: ["Dumbbell Concentration Curl"],
    equipment: "dumbbell",
    pattern: "curl",
    muscles: { biceps: 1 },
    unilateral: true,
    reps: [10, 15],
    cue: "Brace the elbow on the inner thigh; curl and squeeze without moving the arm.",
  },
  {
    id: "db-spider-curl",
    name: "Dumbbell Spider Curl",
    aliases: ["Spider Curl"],
    equipment: "dumbbell",
    pattern: "curl",
    muscles: { biceps: 1 },
    reps: [10, 15],
    cue: "Chest on an incline bench, arms hanging straight down; curl with no swing.",
  },
  {
    id: "ez-bar-spider-curl",
    name: "EZ-Bar Spider Curl",
    equipment: "ezBar",
    pattern: "curl",
    muscles: { biceps: 1 },
    reps: [10, 15],
    cue: "Lie chest-down on an incline bench and curl the bar with arms vertical.",
  },
  {
    id: "cable-curl",
    name: "Cable Curl",
    aliases: ["Cable Bar Curl", "Straight-Bar Cable Curl"],
    equipment: "cable",
    pattern: "curl",
    muscles: { biceps: 1 },
    reps: [10, 15],
    cue: "Stand close to a low pulley; curl with the elbows fixed at your sides.",
  },
  {
    id: "cable-curl-single",
    name: "Single-Arm Cable Curl",
    aliases: ["One-Arm Cable Curl"],
    equipment: "cable",
    pattern: "curl",
    muscles: { biceps: 1 },
    unilateral: true,
    reps: [10, 15],
    cue: "Face the pulley and curl one handle while holding the elbow still.",
  },
  {
    id: "bayesian-curl",
    name: "Bayesian Cable Curl",
    aliases: ["Bayesian Curl", "Behind-the-Body Cable Curl"],
    equipment: "cable",
    pattern: "curl",
    muscles: { biceps: 1 },
    unilateral: true,
    reps: [10, 15],
    cue: "Face away from the pulley; let the arm trail behind you, then curl.",
  },
  {
    id: "cable-curl-high",
    name: "Overhead Cable Curl",
    aliases: ["High Cable Curl", "Double Biceps Cable Curl"],
    equipment: "cable",
    pattern: "curl",
    muscles: { biceps: 1 },
    reps: [10, 15],
    cue: "Arms out at shoulder height between high pulleys; curl hands toward the head.",
  },
  {
    id: "zottman-curl",
    name: "Zottman Curl",
    equipment: "dumbbell",
    pattern: "curl",
    muscles: { biceps: 1, forearms: 0.5 },
    reps: [8, 12],
    cue: "Curl palms up, rotate palms down at the top, then lower slowly.",
  },
  {
    id: "band-curl",
    name: "Band Curl",
    equipment: "band",
    pattern: "curl",
    muscles: { biceps: 1 },
    reps: [12, 20],
    cue: "Stand on the band and curl, squeezing hard where the tension peaks.",
  },

  // Triceps
  {
    id: "cable-pushdown-rope",
    name: "Rope Pushdown",
    aliases: ["Triceps Rope Pushdown", "Rope Triceps Extension"],
    equipment: "cable",
    pattern: "tricepsExtension",
    muscles: { triceps: 1 },
    reps: [10, 15],
    cue: "Elbows pinned to your sides; push down and spread the rope at the bottom.",
  },
  {
    id: "cable-pushdown-bar",
    name: "Bar Pushdown",
    aliases: ["Triceps Pushdown", "Straight-Bar Pushdown", "V-Bar Pushdown", "Cable Pushdown"],
    equipment: "cable",
    pattern: "tricepsExtension",
    muscles: { triceps: 1 },
    reps: [10, 15],
    cue: "Lean slightly forward, keep the elbows still, and press the bar to the thighs.",
  },
  {
    id: "cable-pushdown-single",
    name: "Single-Arm Cable Pushdown",
    aliases: ["One-Arm Pushdown"],
    equipment: "cable",
    pattern: "tricepsExtension",
    muscles: { triceps: 1 },
    unilateral: true,
    reps: [10, 15],
    cue: "Use a single handle; extend fully with the elbow tucked at your side.",
  },
  {
    id: "cable-overhead-extension",
    name: "Overhead Cable Triceps Extension",
    aliases: ["Overhead Rope Extension", "Cable Overhead Extension"],
    equipment: "cable",
    pattern: "tricepsExtension",
    muscles: { triceps: 1 },
    reps: [10, 15],
    cue: "Face away from the pulley; let the rope reach behind the head, then extend.",
  },
  {
    id: "cable-overhead-extension-single",
    name: "Single-Arm Overhead Cable Extension",
    equipment: "cable",
    pattern: "tricepsExtension",
    muscles: { triceps: 1 },
    unilateral: true,
    reps: [10, 15],
    cue: "Point the elbow up; lower the handle behind the head and extend fully.",
  },
  {
    id: "cable-cross-body-extension",
    name: "Cross-Body Cable Extension",
    aliases: ["Katana Extension"],
    equipment: "cable",
    pattern: "tricepsExtension",
    muscles: { triceps: 1 },
    unilateral: true,
    reps: [10, 15],
    cue: "Pull from the opposite high pulley and extend the arm across the body.",
  },
  {
    id: "ez-bar-skull-crusher",
    name: "EZ-Bar Skull Crusher",
    aliases: ["Skull Crusher", "Skullcrusher", "Lying Triceps Extension"],
    equipment: "ezBar",
    pattern: "tricepsExtension",
    muscles: { triceps: 1 },
    reps: [8, 12],
    cue: "Lower the bar just behind the head with the elbows angled slightly back.",
  },
  {
    id: "db-skull-crusher",
    name: "Dumbbell Skull Crusher",
    aliases: ["Dumbbell Lying Triceps Extension"],
    equipment: "dumbbell",
    pattern: "tricepsExtension",
    muscles: { triceps: 1 },
    reps: [10, 15],
    cue: "Palms facing in; lower the dumbbells beside the head, then extend.",
  },
  {
    id: "ez-bar-overhead-extension",
    name: "EZ-Bar Overhead Triceps Extension",
    aliases: ["French Press", "Overhead EZ-Bar Extension"],
    equipment: "ezBar",
    pattern: "tricepsExtension",
    muscles: { triceps: 1 },
    reps: [8, 12],
    cue: "Keep the elbows narrow; lower the bar behind the head for a deep stretch.",
  },
  {
    id: "db-overhead-extension",
    name: "Dumbbell Overhead Triceps Extension",
    aliases: ["Seated Dumbbell Triceps Extension", "Two-Hand Overhead Extension"],
    equipment: "dumbbell",
    pattern: "tricepsExtension",
    muscles: { triceps: 1 },
    reps: [10, 15],
    cue: "Cup one dumbbell with both hands; lower it deep behind the head, then extend.",
  },
  {
    id: "db-overhead-extension-single",
    name: "Single-Arm Dumbbell Overhead Extension",
    equipment: "dumbbell",
    pattern: "tricepsExtension",
    muscles: { triceps: 1 },
    unilateral: true,
    reps: [10, 15],
    cue: "Keep the elbow pointing up; lower behind the head and press to lockout.",
  },
  {
    id: "jm-press",
    name: "JM Press",
    equipment: "barbell",
    pattern: "tricepsExtension",
    muscles: { triceps: 1 },
    reps: [6, 10],
    cue: "Lower the bar toward the chin by letting the elbows travel forward; press up.",
  },
  {
    id: "smith-jm-press",
    name: "Smith Machine JM Press",
    aliases: ["Smith JM Press"],
    equipment: "smith",
    pattern: "tricepsExtension",
    muscles: { triceps: 1 },
    reps: [8, 12],
    cue: "Let the elbows drift forward as the bar drops toward the upper chest.",
  },
  {
    id: "machine-triceps-extension",
    name: "Machine Triceps Extension",
    aliases: ["Triceps Extension Machine"],
    equipment: "machine",
    pattern: "tricepsExtension",
    muscles: { triceps: 1 },
    reps: [10, 15],
    cue: "Align the elbows with the pivot; extend fully and resist on the way back.",
  },
  {
    id: "db-kickback",
    name: "Dumbbell Kickback",
    aliases: ["Triceps Kickback"],
    equipment: "dumbbell",
    pattern: "tricepsExtension",
    muscles: { triceps: 1 },
    unilateral: true,
    reps: [12, 15],
    cue: "Upper arm parallel to the floor; straighten the elbow without swinging.",
  },
  {
    id: "cable-triceps-kickback",
    name: "Cable Triceps Kickback",
    equipment: "cable",
    pattern: "tricepsExtension",
    muscles: { triceps: 1 },
    unilateral: true,
    reps: [12, 15],
    cue: "Hinge forward with the upper arm by your side; extend the handle straight back.",
  },
  {
    id: "band-pushdown",
    name: "Band Pushdown",
    equipment: "band",
    pattern: "tricepsExtension",
    muscles: { triceps: 1 },
    reps: [15, 25],
    cue: "Anchor the band high; extend down with the elbows fixed at your sides.",
  },
  {
    id: "close-grip-bench-press",
    name: "Close-Grip Bench Press",
    aliases: ["CGBP", "Close-Grip Bench"],
    equipment: "barbell",
    pattern: "horizontalPress",
    muscles: { triceps: 1, chest: 0.5, frontDelts: 0.5 },
    reps: [6, 10],
    cue: "Hands about shoulder-width, elbows tucked; touch the lower chest and press.",
  },
  {
    id: "smith-close-grip-bench-press",
    name: "Smith Machine Close-Grip Bench Press",
    equipment: "smith",
    pattern: "horizontalPress",
    muscles: { triceps: 1, chest: 0.5, frontDelts: 0.5 },
    reps: [8, 12],
    cue: "Narrow grip and tucked elbows; lower to the sternum along the track.",
  },
  {
    id: "diamond-push-up",
    name: "Diamond Push-Up",
    aliases: ["Close-Grip Push-Up"],
    equipment: "bodyweight",
    load: "bodyweight",
    pattern: "horizontalPress",
    muscles: { triceps: 1, chest: 0.5, frontDelts: 0.5 },
    reps: [8, 15],
    cue: "Hands together under the chest; keep the elbows close as you lower.",
  },
  {
    id: "triceps-dip",
    name: "Triceps Dip",
    aliases: ["Dip", "Parallel Bar Dip"],
    equipment: "bodyweight",
    load: "bodyweight",
    pattern: "dip",
    muscles: { triceps: 1, chest: 0.5, frontDelts: 0.5 },
    reps: [6, 12],
    cue: "Stay upright with elbows back; lower to about 90° and lock out fully.",
  },
  {
    id: "bench-dip",
    name: "Bench Dip",
    equipment: "bodyweight",
    load: "bodyweight",
    pattern: "dip",
    muscles: { triceps: 1, frontDelts: 0.5 },
    reps: [10, 20],
    cue: "Hands on a bench behind you; lower until the elbows reach 90°, then press.",
  },
  {
    id: "machine-dip",
    name: "Seated Dip Machine",
    aliases: ["Dip Machine", "Machine Dip"],
    equipment: "machine",
    pattern: "dip",
    muscles: { triceps: 1, chest: 0.5 },
    reps: [8, 12],
    cue: "Sit tall, push the handles down to full lockout, and control the rise.",
  },

  // Forearms
  {
    id: "ez-bar-reverse-curl",
    name: "EZ-Bar Reverse Curl",
    aliases: ["Reverse Curl", "Reverse-Grip Curl"],
    equipment: "ezBar",
    pattern: "curl",
    muscles: { forearms: 1, biceps: 0.5 },
    reps: [10, 15],
    cue: "Overhand grip; curl with the wrists straight and the elbows at your sides.",
  },
  {
    id: "db-reverse-curl",
    name: "Dumbbell Reverse Curl",
    equipment: "dumbbell",
    pattern: "curl",
    muscles: { forearms: 1, biceps: 0.5 },
    reps: [10, 15],
    cue: "Palms down; curl both dumbbells up without letting the wrists drop.",
  },
  {
    id: "cable-reverse-curl",
    name: "Cable Reverse Curl",
    equipment: "cable",
    pattern: "curl",
    muscles: { forearms: 1, biceps: 0.5 },
    reps: [10, 15],
    cue: "Overhand grip on a straight bar; curl slowly and keep the knuckles up.",
  },
  {
    id: "barbell-wrist-curl",
    name: "Barbell Wrist Curl",
    aliases: ["Wrist Curl"],
    equipment: "barbell",
    pattern: "wrist",
    muscles: { forearms: 1 },
    reps: [12, 20],
    cue: "Forearms on the thighs, palms up; let the bar roll to the fingers, then curl.",
  },
  {
    id: "db-wrist-curl",
    name: "Dumbbell Wrist Curl",
    equipment: "dumbbell",
    pattern: "wrist",
    muscles: { forearms: 1 },
    reps: [12, 20],
    cue: "Rest the forearm on a bench, palm up; curl the wrist through its full range.",
  },
  {
    id: "barbell-reverse-wrist-curl",
    name: "Barbell Reverse Wrist Curl",
    aliases: ["Reverse Wrist Curl", "Wrist Extension"],
    equipment: "barbell",
    pattern: "wrist",
    muscles: { forearms: 1 },
    reps: [12, 20],
    cue: "Palms down over the knees; lift the knuckles and lower slowly.",
  },
  {
    id: "db-reverse-wrist-curl",
    name: "Dumbbell Reverse Wrist Curl",
    equipment: "dumbbell",
    pattern: "wrist",
    muscles: { forearms: 1 },
    reps: [12, 20],
    cue: "Palm down with the forearm supported; raise the back of the hand toward you.",
  },
  {
    id: "cable-wrist-curl",
    name: "Cable Wrist Curl",
    equipment: "cable",
    pattern: "wrist",
    muscles: { forearms: 1 },
    reps: [12, 20],
    cue: "Kneel at a low pulley with forearms on a bench; curl the handle up.",
  },
  {
    id: "behind-back-wrist-curl",
    name: "Behind-the-Back Wrist Curl",
    equipment: "barbell",
    pattern: "wrist",
    muscles: { forearms: 1 },
    reps: [12, 20],
    cue: "Hold the bar behind your hips and curl it up using only the wrists.",
  },

  // ─── Legs ─────────────────────────────────────────────────────────────────
  // Squats
  {
    id: "barbell-back-squat",
    name: "Barbell Back Squat",
    aliases: ["Back Squat", "Squat"],
    equipment: "barbell",
    pattern: "squat",
    muscles: { quads: 1, glutes: 0.5, adductors: 0.5 },
    reps: [5, 8],
    cue: "Brace, sit down between the hips, and keep the knees tracking over the toes.",
  },
  {
    id: "high-bar-squat",
    name: "High-Bar Back Squat",
    aliases: ["High-Bar Squat", "Olympic Squat"],
    equipment: "barbell",
    pattern: "squat",
    muscles: { quads: 1, glutes: 0.5, adductors: 0.5 },
    reps: [6, 10],
    cue: "Bar on the traps, torso upright; squat deep with the knees traveling forward.",
  },
  {
    id: "low-bar-squat",
    name: "Low-Bar Back Squat",
    aliases: ["Low-Bar Squat"],
    equipment: "barbell",
    pattern: "squat",
    muscles: { quads: 1, glutes: 1, adductors: 0.5 },
    reps: [5, 8],
    cue: "Bar below the traps; lean slightly more and push the floor away.",
  },
  {
    id: "pause-squat",
    name: "Pause Squat",
    aliases: ["Paused Back Squat"],
    equipment: "barbell",
    pattern: "squat",
    muscles: { quads: 1, glutes: 0.5, adductors: 0.5 },
    reps: [4, 8],
    cue: "Hold two seconds in the hole while staying tight, then drive up.",
  },
  {
    id: "front-squat",
    name: "Barbell Front Squat",
    aliases: ["Front Squat"],
    equipment: "barbell",
    pattern: "squat",
    muscles: { quads: 1, glutes: 0.5, upperBack: 0.5 },
    reps: [6, 10],
    cue: "Elbows high, torso upright; sit straight down between the heels.",
  },
  {
    id: "safety-bar-squat",
    name: "Safety Bar Squat",
    aliases: ["SSB Squat", "Safety Squat Bar Squat"],
    equipment: "barbell",
    pattern: "squat",
    muscles: { quads: 1, glutes: 0.5, upperBack: 0.5 },
    reps: [6, 10],
    cue: "Hold the handles and keep the chest up against the bar's forward pull.",
  },
  {
    id: "smith-squat",
    name: "Smith Machine Squat",
    aliases: ["Smith Squat"],
    equipment: "smith",
    pattern: "squat",
    muscles: { quads: 1, glutes: 0.5, adductors: 0.5 },
    reps: [8, 12],
    cue: "Feet slightly ahead of the bar; descend deep with a vertical torso.",
  },
  {
    id: "hack-squat",
    name: "Hack Squat",
    aliases: ["Machine Hack Squat"],
    equipment: "plateLoaded",
    pattern: "squat",
    muscles: { quads: 1, glutes: 0.5 },
    reps: [8, 12],
    cue: "Back flat on the pad; lower until the thighs pass parallel, knees forward.",
  },
  {
    id: "reverse-hack-squat",
    name: "Reverse Hack Squat",
    equipment: "plateLoaded",
    pattern: "squat",
    muscles: { glutes: 1, quads: 0.5, hamstrings: 0.5 },
    reps: [8, 12],
    cue: "Face the pad, push the hips back, and drive up through the whole foot.",
  },
  {
    id: "pendulum-squat",
    name: "Pendulum Squat",
    equipment: "plateLoaded",
    pattern: "squat",
    muscles: { quads: 1, glutes: 0.5 },
    reps: [8, 12],
    cue: "Shoulders under the pads; sink as deep as possible and drive through midfoot.",
  },
  {
    id: "belt-squat",
    name: "Belt Squat",
    equipment: "plateLoaded",
    pattern: "squat",
    muscles: { quads: 1, glutes: 0.5, adductors: 0.5 },
    reps: [8, 12],
    cue: "Belt on the hips, torso upright; squat deep with no load on the spine.",
  },
  {
    id: "v-squat",
    name: "V-Squat",
    aliases: ["Power Squat Machine"],
    equipment: "plateLoaded",
    pattern: "squat",
    muscles: { quads: 1, glutes: 0.5 },
    reps: [8, 12],
    cue: "Shoulders under the pads; control the descent and push through the heels.",
  },
  {
    id: "goblet-squat",
    name: "Goblet Squat",
    aliases: ["Dumbbell Goblet Squat", "Kettlebell Goblet Squat"],
    equipment: "dumbbell",
    pattern: "squat",
    muscles: { quads: 1, glutes: 0.5, adductors: 0.5 },
    reps: [8, 15],
    cue: "Hold the weight at the chest; sit between the knees with elbows inside them.",
  },

  // Leg press
  {
    id: "leg-press",
    name: "Leg Press",
    aliases: ["45-Degree Leg Press", "Sled Leg Press"],
    equipment: "plateLoaded",
    pattern: "legPress",
    muscles: { quads: 1, glutes: 0.5 },
    reps: [8, 12],
    cue: "Lower until the knees are deep while the hips stay down on the seat.",
  },
  {
    id: "leg-press-seated",
    name: "Seated Leg Press",
    aliases: ["Horizontal Leg Press", "Leg Press Machine"],
    equipment: "machine",
    pattern: "legPress",
    muscles: { quads: 1, glutes: 0.5 },
    reps: [10, 15],
    cue: "Back flat on the pad; bring the knees toward the chest and press out.",
  },
  {
    id: "leg-press-single",
    name: "Single-Leg Leg Press",
    aliases: ["Single-Leg Press"],
    equipment: "plateLoaded",
    pattern: "legPress",
    muscles: { quads: 1, glutes: 0.5 },
    unilateral: true,
    reps: [10, 15],
    cue: "One foot centered on the platform; lower slowly with the hip staying down.",
  },
  {
    id: "leg-press-high-foot",
    name: "High-Foot Leg Press",
    aliases: ["Wide-Stance Leg Press"],
    equipment: "plateLoaded",
    pattern: "legPress",
    muscles: { glutes: 1, quads: 0.5, hamstrings: 0.5 },
    reps: [10, 15],
    cue: "Place the feet high and wide; drive through the heels without the hips lifting.",
  },

  // Lunges and split squats
  {
    id: "db-bulgarian-split-squat",
    name: "Dumbbell Bulgarian Split Squat",
    aliases: ["Bulgarian Split Squat", "BSS", "Rear-Foot-Elevated Split Squat"],
    equipment: "dumbbell",
    pattern: "lunge",
    muscles: { quads: 1, glutes: 1, adductors: 0.5 },
    unilateral: true,
    reps: [8, 12],
    cue: "Rear foot on a bench; drop the back knee straight down, front foot flat.",
  },
  {
    id: "smith-bulgarian-split-squat",
    name: "Smith Machine Bulgarian Split Squat",
    aliases: ["Smith Bulgarian Split Squat"],
    equipment: "smith",
    pattern: "lunge",
    muscles: { quads: 1, glutes: 1, adductors: 0.5 },
    unilateral: true,
    reps: [8, 12],
    cue: "Rear foot on a bench behind the bar; lower straight down along the track.",
  },
  {
    id: "db-split-squat",
    name: "Dumbbell Split Squat",
    aliases: ["Split Squat", "Static Lunge"],
    equipment: "dumbbell",
    pattern: "lunge",
    muscles: { quads: 1, glutes: 0.5, adductors: 0.5 },
    unilateral: true,
    reps: [8, 12],
    cue: "Staggered stance, feet hip-width; lower the back knee toward the floor.",
  },
  {
    id: "smith-split-squat",
    name: "Smith Machine Split Squat",
    equipment: "smith",
    pattern: "lunge",
    muscles: { quads: 1, glutes: 0.5, adductors: 0.5 },
    unilateral: true,
    reps: [8, 12],
    cue: "Front foot ahead of the bar; sink the back knee down and drive up evenly.",
  },
  {
    id: "db-walking-lunge",
    name: "Dumbbell Walking Lunge",
    aliases: ["Walking Lunge"],
    equipment: "dumbbell",
    pattern: "lunge",
    muscles: { quads: 1, glutes: 1, adductors: 0.5 },
    unilateral: true,
    reps: [10, 15],
    cue: "Take long steps and lower the rear knee gently toward the floor.",
  },
  {
    id: "db-reverse-lunge",
    name: "Dumbbell Reverse Lunge",
    aliases: ["Reverse Lunge"],
    equipment: "dumbbell",
    pattern: "lunge",
    muscles: { quads: 1, glutes: 1 },
    unilateral: true,
    reps: [8, 12],
    cue: "Step back and drop the rear knee; push through the front heel to return.",
  },
  {
    id: "db-deficit-reverse-lunge",
    name: "Deficit Reverse Lunge",
    equipment: "dumbbell",
    pattern: "lunge",
    muscles: { glutes: 1, quads: 1 },
    unilateral: true,
    reps: [8, 12],
    cue: "Stand on a low step and reach back deep so the front hip fully flexes.",
  },
  {
    id: "barbell-reverse-lunge",
    name: "Barbell Reverse Lunge",
    equipment: "barbell",
    pattern: "lunge",
    muscles: { quads: 1, glutes: 1 },
    unilateral: true,
    reps: [8, 12],
    cue: "Brace with the bar on the traps and step back into each rep under control.",
  },
  {
    id: "smith-reverse-lunge",
    name: "Smith Machine Reverse Lunge",
    equipment: "smith",
    pattern: "lunge",
    muscles: { quads: 1, glutes: 1 },
    unilateral: true,
    reps: [8, 12],
    cue: "Step one foot back under the bar and lower straight down.",
  },
  {
    id: "db-lunge",
    name: "Dumbbell Forward Lunge",
    aliases: ["Forward Lunge", "Dumbbell Lunge"],
    equipment: "dumbbell",
    pattern: "lunge",
    muscles: { quads: 1, glutes: 0.5 },
    unilateral: true,
    reps: [8, 12],
    cue: "Step forward, lower to a controlled depth, and push back to standing.",
  },
  {
    id: "db-step-up",
    name: "Dumbbell Step-Up",
    aliases: ["Step-Up"],
    equipment: "dumbbell",
    pattern: "lunge",
    muscles: { quads: 1, glutes: 0.5 },
    unilateral: true,
    reps: [8, 12],
    cue: "Plant the whole foot on the box and stand up without pushing off the back leg.",
  },

  // Knee extension
  {
    id: "leg-extension",
    name: "Leg Extension",
    aliases: ["Quad Extension", "Knee Extension"],
    equipment: "machine",
    pattern: "legExtension",
    muscles: { quads: 1 },
    reps: [10, 15],
    cue: "Align the knee with the pivot; kick up to lockout and lower slowly.",
  },
  {
    id: "leg-extension-single",
    name: "Single-Leg Leg Extension",
    aliases: ["Single-Leg Extension"],
    equipment: "machine",
    pattern: "legExtension",
    muscles: { quads: 1 },
    unilateral: true,
    reps: [10, 15],
    cue: "Work one leg at a time; pause briefly with the knee fully straight.",
  },
  {
    id: "sissy-squat",
    name: "Sissy Squat",
    equipment: "bodyweight",
    load: "bodyweight",
    pattern: "legExtension",
    muscles: { quads: 1 },
    reps: [8, 15],
    cue: "Rise onto the toes and lean back as the knees travel far forward; stand tall.",
  },
  {
    id: "reverse-nordic",
    name: "Reverse Nordic",
    aliases: ["Reverse Nordic Curl"],
    equipment: "bodyweight",
    load: "bodyweight",
    pattern: "legExtension",
    muscles: { quads: 1 },
    reps: [8, 12],
    cue: "Kneel upright with hips straight; lean back only as far as you can control.",
  },

  // Hinges
  {
    id: "conventional-deadlift",
    name: "Conventional Deadlift",
    aliases: ["Deadlift", "Barbell Deadlift"],
    equipment: "barbell",
    pattern: "hinge",
    muscles: { glutes: 1, hamstrings: 0.5, lowerBack: 0.5, quads: 0.5 },
    reps: [5, 8],
    cue: "Bar over midfoot; pull the slack out, then push the floor away.",
  },
  {
    id: "sumo-deadlift",
    name: "Sumo Deadlift",
    equipment: "barbell",
    pattern: "hinge",
    muscles: { glutes: 1, adductors: 0.5, quads: 0.5, lowerBack: 0.5 },
    reps: [5, 8],
    cue: "Wide stance, hands inside the knees; spread the floor and keep the chest up.",
  },
  {
    id: "trap-bar-deadlift",
    name: "Trap Bar Deadlift",
    aliases: ["Hex Bar Deadlift"],
    equipment: "trapBar",
    pattern: "hinge",
    muscles: { glutes: 1, quads: 0.5, hamstrings: 0.5, lowerBack: 0.5 },
    reps: [5, 8],
    cue: "Stand centered, grip the handles, and drive up with hips and knees together.",
  },
  {
    id: "rack-pull",
    name: "Rack Pull",
    aliases: ["Block Pull"],
    equipment: "barbell",
    pattern: "hinge",
    muscles: { lowerBack: 1, glutes: 0.5, traps: 0.5 },
    reps: [5, 8],
    cue: "Set the bar just below the knees; lock the hips through without leaning back.",
  },
  {
    id: "barbell-rdl",
    name: "Barbell Romanian Deadlift",
    aliases: ["RDL", "Romanian Deadlift", "Barbell RDL"],
    equipment: "barbell",
    pattern: "hinge",
    muscles: { hamstrings: 1, glutes: 0.5, lowerBack: 0.5 },
    reps: [6, 10],
    cue: "Soft knees; push the hips back until the hamstrings stretch, bar on the thighs.",
  },
  {
    id: "db-rdl",
    name: "Dumbbell Romanian Deadlift",
    aliases: ["DB RDL", "Dumbbell RDL"],
    equipment: "dumbbell",
    pattern: "hinge",
    muscles: { hamstrings: 1, glutes: 0.5, lowerBack: 0.5 },
    reps: [8, 12],
    cue: "Slide the dumbbells down the thighs by hinging back; keep the spine neutral.",
  },
  {
    id: "db-rdl-single-leg",
    name: "Single-Leg Dumbbell RDL",
    aliases: ["Single-Leg RDL", "Single-Leg Romanian Deadlift"],
    equipment: "dumbbell",
    pattern: "hinge",
    muscles: { hamstrings: 1, glutes: 1 },
    unilateral: true,
    reps: [8, 12],
    cue: "Hinge on one leg with the hips square; reach the dumbbell toward the floor.",
  },
  {
    id: "smith-rdl",
    name: "Smith Machine RDL",
    aliases: ["Smith Romanian Deadlift"],
    equipment: "smith",
    pattern: "hinge",
    muscles: { hamstrings: 1, glutes: 0.5, lowerBack: 0.5 },
    reps: [8, 12],
    cue: "Stand close to the bar and push the hips back until the hamstrings stretch.",
  },
  {
    id: "stiff-leg-deadlift",
    name: "Stiff-Leg Deadlift",
    aliases: ["SLDL", "Stiff-Legged Deadlift"],
    equipment: "barbell",
    pattern: "hinge",
    muscles: { hamstrings: 1, glutes: 0.5, lowerBack: 0.5 },
    reps: [6, 10],
    cue: "Knees nearly locked; hinge and lower the bar to mid-shin or the floor.",
  },
  {
    id: "good-morning",
    name: "Good Morning",
    aliases: ["Barbell Good Morning"],
    equipment: "barbell",
    pattern: "hinge",
    muscles: { hamstrings: 1, lowerBack: 0.5, glutes: 0.5 },
    reps: [8, 12],
    cue: "Bar on the back, soft knees; bow forward from the hips with a flat back.",
  },
  {
    id: "cable-pull-through",
    name: "Cable Pull-Through",
    aliases: ["Pull-Through"],
    equipment: "cable",
    pattern: "hinge",
    muscles: { glutes: 1, hamstrings: 0.5 },
    reps: [10, 15],
    cue: "Face away from a low pulley; hinge back, then snap the hips forward.",
  },
  {
    id: "kb-swing",
    name: "Kettlebell Swing",
    aliases: ["KB Swing", "Russian Swing"],
    equipment: "kettlebell",
    pattern: "hinge",
    muscles: { glutes: 1, hamstrings: 0.5 },
    reps: [12, 20],
    cue: "Hike the bell back, then drive the hips forward so it floats to chest height.",
  },

  // Back extensions
  {
    id: "back-extension-45",
    name: "45° Back Extension",
    aliases: ["Back Extension", "Hyperextension", "Roman Chair Back Extension"],
    equipment: "bodyweight",
    load: "bodyweight",
    pattern: "backExtension",
    muscles: { glutes: 1, hamstrings: 0.5, lowerBack: 0.5 },
    reps: [10, 15],
    cue: "Hips just above the pad; hinge down and squeeze the glutes to rise to neutral.",
  },
  {
    id: "back-extension-machine",
    name: "Machine Back Extension",
    aliases: ["Lower Back Machine"],
    equipment: "machine",
    pattern: "backExtension",
    muscles: { lowerBack: 1, glutes: 0.5 },
    reps: [10, 15],
    cue: "Seat the hips firmly; extend against the pad smoothly without snapping back.",
  },
  {
    id: "reverse-hyper",
    name: "Reverse Hyperextension",
    aliases: ["Reverse Hyper"],
    equipment: "plateLoaded",
    pattern: "backExtension",
    muscles: { glutes: 1, hamstrings: 0.5, lowerBack: 0.5 },
    reps: [10, 15],
    cue: "Lie prone on the pad; swing the legs up to hip level using the glutes.",
  },

  // Hip thrusts and glute isolation
  {
    id: "barbell-hip-thrust",
    name: "Barbell Hip Thrust",
    aliases: ["Hip Thrust"],
    equipment: "barbell",
    pattern: "hipThrust",
    muscles: { glutes: 1 },
    reps: [8, 12],
    cue: "Upper back on a bench, chin tucked; drive the hips up until thighs are level.",
  },
  {
    id: "machine-hip-thrust",
    name: "Machine Hip Thrust",
    aliases: ["Hip Thrust Machine", "Glute Drive"],
    equipment: "plateLoaded",
    pattern: "hipThrust",
    muscles: { glutes: 1 },
    reps: [8, 12],
    cue: "Belt over the hips, feet flat; thrust up and pause at full lockout.",
  },
  {
    id: "smith-hip-thrust",
    name: "Smith Machine Hip Thrust",
    aliases: ["Smith Hip Thrust"],
    equipment: "smith",
    pattern: "hipThrust",
    muscles: { glutes: 1 },
    reps: [8, 12],
    cue: "Pad the bar, set up under it, and drive straight up the track.",
  },
  {
    id: "db-hip-thrust",
    name: "Dumbbell Hip Thrust",
    equipment: "dumbbell",
    pattern: "hipThrust",
    muscles: { glutes: 1 },
    reps: [10, 15],
    cue: "Hold the dumbbell on the hip crease; press through the heels to full extension.",
  },
  {
    id: "hip-thrust-single-leg",
    name: "Single-Leg Hip Thrust",
    equipment: "bodyweight",
    load: "bodyweight",
    pattern: "hipThrust",
    muscles: { glutes: 1 },
    unilateral: true,
    reps: [10, 15],
    cue: "One foot planted, the other lifted; drive the hips up level with no twisting.",
  },
  {
    id: "barbell-glute-bridge",
    name: "Barbell Glute Bridge",
    equipment: "barbell",
    pattern: "hipThrust",
    muscles: { glutes: 1 },
    reps: [8, 12],
    cue: "Lie on the floor with the bar on the hips; squeeze the glutes to lift, pause.",
  },
  {
    id: "glute-bridge",
    name: "Glute Bridge",
    equipment: "bodyweight",
    load: "bodyweight",
    pattern: "hipThrust",
    muscles: { glutes: 1 },
    reps: [12, 20],
    cue: "Feet close to the hips; push through the heels and squeeze at the top.",
  },
  {
    id: "cable-glute-kickback",
    name: "Cable Glute Kickback",
    aliases: ["Cable Kickback"],
    equipment: "cable",
    pattern: "hipThrust",
    muscles: { glutes: 1 },
    unilateral: true,
    reps: [10, 15],
    cue: "Ankle strap on; drive the leg back and up while the lower back stays still.",
  },
  {
    id: "machine-glute-kickback",
    name: "Glute Kickback Machine",
    aliases: ["Glute Machine", "Machine Glute Kickback"],
    equipment: "machine",
    pattern: "hipThrust",
    muscles: { glutes: 1 },
    unilateral: true,
    reps: [10, 15],
    cue: "Brace on the pads and push the platform back through the heel.",
  },

  // Leg curls
  {
    id: "seated-leg-curl",
    name: "Seated Leg Curl",
    aliases: ["Seated Hamstring Curl"],
    equipment: "machine",
    pattern: "legCurl",
    muscles: { hamstrings: 1 },
    reps: [10, 15],
    cue: "Lock the thigh pad down, lean forward slightly, and curl the heels under.",
  },
  {
    id: "seated-leg-curl-single",
    name: "Single-Leg Seated Leg Curl",
    equipment: "machine",
    pattern: "legCurl",
    muscles: { hamstrings: 1 },
    unilateral: true,
    reps: [10, 15],
    cue: "Curl one leg at a time with the thigh pad tight and the hips square.",
  },
  {
    id: "lying-leg-curl",
    name: "Lying Leg Curl",
    aliases: ["Prone Leg Curl", "Lying Hamstring Curl"],
    equipment: "machine",
    pattern: "legCurl",
    muscles: { hamstrings: 1 },
    reps: [10, 15],
    cue: "Hips pressed into the pad; curl the heels toward the glutes and lower slowly.",
  },
  {
    id: "standing-leg-curl-single",
    name: "Standing Single-Leg Curl",
    aliases: ["Standing Leg Curl"],
    equipment: "machine",
    pattern: "legCurl",
    muscles: { hamstrings: 1 },
    unilateral: true,
    reps: [10, 15],
    cue: "Brace on the frame and curl one heel up without hiking the hip.",
  },
  {
    id: "cable-leg-curl",
    name: "Cable Leg Curl",
    aliases: ["Standing Cable Leg Curl"],
    equipment: "cable",
    pattern: "legCurl",
    muscles: { hamstrings: 1 },
    unilateral: true,
    reps: [10, 15],
    cue: "Ankle strap on a low pulley; curl the heel toward the glute.",
  },
  {
    id: "db-leg-curl",
    name: "Dumbbell Leg Curl",
    aliases: ["Lying Dumbbell Leg Curl"],
    equipment: "dumbbell",
    pattern: "legCurl",
    muscles: { hamstrings: 1 },
    reps: [10, 15],
    cue: "Lie face down with a dumbbell between the feet; curl up and lower slowly.",
  },
  {
    id: "nordic-curl",
    name: "Nordic Hamstring Curl",
    aliases: ["Nordic Curl", "Nordics"],
    equipment: "bodyweight",
    load: "bodyweight",
    pattern: "legCurl",
    muscles: { hamstrings: 1 },
    reps: [4, 8],
    cue: "Anchor the ankles, keep the hips straight, and lower as slowly as possible.",
  },
  {
    id: "glute-ham-raise",
    name: "Glute-Ham Raise",
    aliases: ["GHR", "Glute Ham Raise"],
    equipment: "bodyweight",
    load: "bodyweight",
    pattern: "legCurl",
    muscles: { hamstrings: 1, glutes: 0.5 },
    reps: [6, 10],
    cue: "Knees behind the pad; lower with the hips straight, then curl back up.",
  },
  {
    id: "sliding-leg-curl",
    name: "Sliding Leg Curl",
    aliases: ["Stability Ball Leg Curl", "Slider Leg Curl"],
    equipment: "bodyweight",
    load: "bodyweight",
    pattern: "legCurl",
    muscles: { hamstrings: 1, glutes: 0.5 },
    reps: [10, 15],
    cue: "Hold a bridge; slide the heels in and out without the hips dropping.",
  },

  // Adductors and abductors
  {
    id: "hip-adduction-machine",
    name: "Hip Adduction Machine",
    aliases: ["Adductor Machine", "Inner Thigh Machine", "Seated Hip Adduction"],
    equipment: "machine",
    pattern: "hipAdduction",
    muscles: { adductors: 1 },
    reps: [12, 20],
    cue: "Start wide in a stretch; squeeze the knees together and control the return.",
  },
  {
    id: "cable-hip-adduction",
    name: "Cable Hip Adduction",
    equipment: "cable",
    pattern: "hipAdduction",
    muscles: { adductors: 1 },
    unilateral: true,
    reps: [12, 15],
    cue: "Strap the near ankle; sweep the leg across the body in front of you.",
  },
  {
    id: "hip-abduction-machine",
    name: "Hip Abduction Machine",
    aliases: ["Abductor Machine", "Outer Thigh Machine", "Seated Hip Abduction"],
    equipment: "machine",
    pattern: "hipAbduction",
    muscles: { glutes: 1 },
    reps: [12, 20],
    cue: "Sit tall or lean forward; press the knees out and control the return.",
  },
  {
    id: "cable-hip-abduction",
    name: "Cable Hip Abduction",
    equipment: "cable",
    pattern: "hipAbduction",
    muscles: { glutes: 1 },
    unilateral: true,
    reps: [12, 15],
    cue: "Strap the far ankle; lift the leg out to the side without leaning.",
  },
  {
    id: "band-hip-abduction",
    name: "Banded Hip Abduction",
    aliases: ["Band Hip Abduction", "Seated Band Abduction"],
    equipment: "band",
    pattern: "hipAbduction",
    muscles: { glutes: 1 },
    reps: [15, 25],
    cue: "Band above the knees; push the knees apart and hold briefly.",
  },

  // Calves
  {
    id: "standing-calf-raise",
    name: "Standing Calf Raise",
    aliases: ["Standing Calf Machine", "Machine Standing Calf Raise"],
    equipment: "machine",
    pattern: "calfRaise",
    muscles: { calves: 1 },
    reps: [10, 15],
    cue: "Pause in the bottom stretch, then rise as high as possible on the toes.",
  },
  {
    id: "seated-calf-raise",
    name: "Seated Calf Raise",
    aliases: ["Seated Calf Machine"],
    equipment: "plateLoaded",
    pattern: "calfRaise",
    muscles: { calves: 1 },
    reps: [12, 20],
    cue: "Pad over the knees; sink the heels deep, pause, and press up fully.",
  },
  {
    id: "leg-press-calf-raise",
    name: "Leg Press Calf Raise",
    aliases: ["Calf Press"],
    equipment: "plateLoaded",
    pattern: "calfRaise",
    muscles: { calves: 1 },
    reps: [10, 15],
    cue: "Balls of the feet on the platform edge; press through a full ankle range.",
  },
  {
    id: "smith-calf-raise",
    name: "Smith Machine Calf Raise",
    aliases: ["Smith Calf Raise"],
    equipment: "smith",
    pattern: "calfRaise",
    muscles: { calves: 1 },
    reps: [10, 15],
    cue: "Stand on a step under the bar; stretch deep at the bottom, then rise high.",
  },
  {
    id: "db-calf-raise-single",
    name: "Single-Leg Dumbbell Calf Raise",
    aliases: ["Single-Leg Calf Raise"],
    equipment: "dumbbell",
    pattern: "calfRaise",
    muscles: { calves: 1 },
    unilateral: true,
    reps: [10, 15],
    cue: "Stand on a step holding a dumbbell; lower slowly and pause at the bottom.",
  },
  {
    id: "donkey-calf-raise",
    name: "Donkey Calf Raise",
    equipment: "machine",
    pattern: "calfRaise",
    muscles: { calves: 1 },
    reps: [10, 15],
    cue: "Hinge forward under the pad; get a deep stretch and rise fully.",
  },

  // ─── Core ─────────────────────────────────────────────────────────────────
  {
    id: "cable-crunch",
    name: "Cable Crunch",
    aliases: ["Kneeling Cable Crunch", "Rope Crunch"],
    equipment: "cable",
    pattern: "crunch",
    muscles: { abs: 1 },
    reps: [10, 15],
    cue: "Kneel, hold the rope by your head, and curl the ribs toward the pelvis.",
  },
  {
    id: "machine-crunch",
    name: "Machine Crunch",
    aliases: ["Ab Crunch Machine", "Crunch Machine"],
    equipment: "machine",
    pattern: "crunch",
    muscles: { abs: 1 },
    reps: [10, 15],
    cue: "Round the spine to crunch down; do not just pull with the arms.",
  },
  {
    id: "crunch",
    name: "Crunch",
    aliases: ["Floor Crunch"],
    equipment: "bodyweight",
    load: "bodyweight",
    pattern: "crunch",
    muscles: { abs: 1 },
    reps: [12, 20],
    cue: "Curl the shoulders off the floor by closing the gap between ribs and hips.",
  },
  {
    id: "decline-sit-up",
    name: "Decline Sit-Up",
    aliases: ["Weighted Decline Sit-Up"],
    equipment: "bodyweight",
    load: "bodyweight",
    pattern: "crunch",
    muscles: { abs: 1 },
    reps: [10, 15],
    cue: "Hook the feet, curl up one vertebra at a time, and lower slowly.",
  },
  {
    id: "hanging-leg-raise",
    name: "Hanging Leg Raise",
    equipment: "bodyweight",
    load: "bodyweight",
    pattern: "legRaise",
    muscles: { abs: 1 },
    reps: [8, 15],
    cue: "Hang still; raise the legs by curling the pelvis up, not just the thighs.",
  },
  {
    id: "hanging-knee-raise",
    name: "Hanging Knee Raise",
    equipment: "bodyweight",
    load: "bodyweight",
    pattern: "legRaise",
    muscles: { abs: 1 },
    reps: [10, 15],
    cue: "Pull the knees toward the chest and tilt the pelvis up; avoid swinging.",
  },
  {
    id: "captains-chair-knee-raise",
    name: "Captain's Chair Knee Raise",
    aliases: ["Roman Chair Knee Raise", "Vertical Knee Raise"],
    equipment: "bodyweight",
    load: "bodyweight",
    pattern: "legRaise",
    muscles: { abs: 1 },
    reps: [10, 15],
    cue: "Back against the pad; lift the knees and curl the hips off the pad.",
  },
  {
    id: "toes-to-bar",
    name: "Toes-to-Bar",
    equipment: "bodyweight",
    load: "bodyweight",
    pattern: "legRaise",
    muscles: { abs: 1 },
    reps: [6, 12],
    cue: "From a hang, lift the feet to touch the bar using the abs with minimal swing.",
  },
  {
    id: "lying-leg-raise",
    name: "Lying Leg Raise",
    equipment: "bodyweight",
    load: "bodyweight",
    pattern: "legRaise",
    muscles: { abs: 1 },
    reps: [12, 20],
    cue: "Press the low back into the floor and lower straight legs without arching.",
  },
  {
    id: "reverse-crunch",
    name: "Reverse Crunch",
    equipment: "bodyweight",
    load: "bodyweight",
    pattern: "legRaise",
    muscles: { abs: 1 },
    reps: [12, 20],
    cue: "Curl the hips off the floor toward the ribs, then lower with control.",
  },
  {
    id: "ab-wheel-rollout",
    name: "Ab Wheel Rollout",
    aliases: ["Ab Roller", "Ab Wheel"],
    equipment: "bodyweight",
    load: "bodyweight",
    pattern: "core",
    muscles: { abs: 1 },
    reps: [8, 12],
    cue: "Keep the ribs tucked; roll out only as far as you can without the back sagging.",
  },
  {
    id: "barbell-rollout",
    name: "Barbell Rollout",
    equipment: "barbell",
    pattern: "core",
    muscles: { abs: 1 },
    reps: [8, 12],
    cue: "Use round plates; roll out with a hollow body and pull back with the abs.",
  },
  {
    id: "pallof-press",
    name: "Pallof Press",
    aliases: ["Anti-Rotation Press"],
    equipment: "cable",
    pattern: "core",
    muscles: { abs: 1 },
    unilateral: true,
    reps: [10, 15],
    cue: "Side-on to the pulley; press the handle out and resist being rotated.",
  },
  {
    id: "cable-woodchop",
    name: "Cable Woodchop",
    aliases: ["Woodchopper"],
    equipment: "cable",
    pattern: "core",
    muscles: { abs: 1 },
    unilateral: true,
    reps: [10, 15],
    cue: "Rotate through the torso, moving the handle diagonally across the body.",
  },
  {
    id: "db-side-bend",
    name: "Dumbbell Side Bend",
    equipment: "dumbbell",
    pattern: "core",
    muscles: { abs: 1 },
    unilateral: true,
    reps: [12, 15],
    cue: "Hold one dumbbell; bend sideways, then pull back up using the obliques.",
  },
  {
    id: "dead-bug",
    name: "Dead Bug",
    equipment: "bodyweight",
    load: "bodyweight",
    pattern: "core",
    muscles: { abs: 1 },
    reps: [8, 12],
    cue: "Low back flat; extend the opposite arm and leg slowly without arching.",
  },
];
